export const CategoriesArray = [
  {
    id: 1,
    requests: 'Pending',
    providername: 'Jacob',
    desc: 'Your home electrition',
    phoneNo: '03202919700',
    image: require('../assets/images/air-conditioner.png'),
  },
  {
    id: 2,
    requests: 'Pending',
    providername: 'Jacob',
    desc: 'Your Carpenter',
    phoneNo: '03202919700',
    image: require('../assets/images/carpenter.png'),
  },
  {
    id: 3,
    serviceName: 'Electrition',
    providername: 'Jacob',
    desc: 'Your home electrition',
    phoneNo: '03202919700',
    image: require('../assets/images/electrician.png'),
  },
  {
    id: 4,
    serviceName: 'Painter',
    providername: 'Jacob',
    desc: 'Your Painter',
    phoneNo: '03202919700',
    image: require('../assets/images/painter.png'),
  },
  {
    id: 5,
    serviceName: 'Beautician',
    providername: 'Jacob',
    desc: 'Your Beautician',
    phoneNo: '03202919700',
    image: require('../assets/images/beautician.png'),
  },
  {
    id: 6,
    serviceName: 'Plumber',
    providername: 'Jacob',
    desc: 'Your Plumber',
    phoneNo: '03202919700',
    image: require('../assets/images/plumber.png'),
  },
  {
    id: 7,
    serviceName: 'Home Appliance',
    providername: 'Jacob',
    desc: 'Your Home Appliance',
    phoneNo: '03202919700',
    image: require('../assets/images/homeappliance.png'),
  },
];

export const ServicesArray = [
  {
    id: 1,
    serviceName: 'Service',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/air-conditioner.png'),
  },
  {
    id: 2,
    serviceName: 'Services Providers',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/carpenter.png'),
  },
  {
    id: 3,
    serviceName: 'Booked Requests',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/booking.png'),
  },
  {
    id: 4,
    serviceName: 'Pending Requests',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/booking.png'),
  },
  {
    id: 5,
    serviceName: 'Comlpeted Requests',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/booking.png'),
  },
  {
    id: 6,
    serviceName: 'Cancled Requests',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/booking.png'),
  },
];
