export const ActionTypes = {
  INSPECTOR_REGISTER: 'INSPECTOR_REGISTER',
  INSPECTOR_LOGIN: 'INSPECTOR_LOGIN',
  VERIFY_OTP: 'VERIFY_OTP',
  INSPECTOR_LOGOUT: 'INSPECTOR_LOGOUT',
  CONSUMER_LOGOUT: 'CONSUMER_LOGOUT',
  CONSUMER_REGISTER: 'CONSUMER_REGISTER',
  CONSUMER_LOGIN: 'CONSUMER_LOGIN',
  CONSUMER_VERIFY_OTP: 'CONSUMER_VERIFY_OTP',
  CONSUMER_UPDATE: 'CONSUMER_UPDATE',
  VEHICLE_UPDATE: 'VEHICLE_UPDATE',
  ASSIGNED_SERVICE_REQUEST: 'ASSIGNED_SERVICE_REQUEST',
  // UPDATE_VEHICLE_DETAIL: 'UPDATE_VEHICLE_DETAIL',
};
