export const ActionTypes = {
  INSPECTOR_REGISTER: 'INSPECTOR_REGISTER',
  INSPECTOR_LOGIN: 'INSPECTOR_LOGIN',
  VERIFY_OTP: 'VERIFY_OTP',

  CONSUMER_REGISTER: 'CONSUMER_REGISTER',
  CONSUMER_LOGIN: 'CONSUMER_LOGIN',
  CONSUMER_VERIFY_OTP: 'CONSUMER_VERIFY_OTP',
  CONSUMER_UPDATE: 'CONSUMER_UPDATE',
  VEHICLE_UPDATE: 'VEHICLE_UPDATE',
};
